src/SundialBundle/Entity/UserLastTask.php
<?php

namespace SundialBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use SundialBundle\Annotations\OpenAirField;

/**
 * UserLastTask
 *
 * @ORM\Table(name="user_last_task")
 * @ORM\Entity(repositoryClass="SundialBundle\Repository\UserLastTaskRepository")
 */
class UserLastTask
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @Assert\NotNull()
     */
    private $user;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="Project")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     * @Assert\NotNull()
     */
    private $project;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="ProjectTask")
     * @ORM\JoinColumn(name="projecttask_id", referencedColumnName="id")
     * @Assert\NotNull()
     */
    private $task;

    function __construct(User $user = null, Project $project = null, ProjectTask $task = null)
    {
        if(!is_null($user))
            $this->user = $user;
        if(!is_null($project))
            $this->project = $project;
        if(!is_null($task))
            $this->task = $task;
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param integer $user
     * @return UserLastTask
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return integer 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set project
     *
     * @param integer $project
     * @return UserLastTask
     */
    public function setProject($project)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return integer 
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Set task
     *
     * @param integer $task
     * @return UserLastTask
     */
    public function setProjectTask($task)
    {
        $this->task = $task;

        return $this;
    }

    /**
     * Get task
     *
     * @return integer 
     */
    public function getProjectTask()
    {
        return $this->task;
    }
}

src/SundialBundle/Form/TaskType.php
<?php

namespace SundialBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    private $em;
    private $container;
    private $token;
    private $timesheetService;

    function __construct(Container $container)
    {
        $this->container = $container;
        $this->em = $this->container->get('doctrine.orm.entity_manager');
        $this->token = $this->container->get('security.token_storage')->getToken();
        $this->timesheetService = $this->container->get('app.timesheet_service');
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $timetypes = $this->em->getRepository('SundialBundle:TimeType')->findAll();
        $defaultTimetype = null;
        $entityUtility = $this->container->get('app.entity_utility');

        $aryTimeTypes = [];
        foreach($timetypes as $objTimetype){
            $aryTimeTypes[$objTimetype->getId()] = $objTimetype->getType();
        }

        // let's get the currently staffed projects
        $day = $this->timesheetService->getDay();
        $aryAssignedProjects = [];
        if(!is_null($day)){
            $aryTimesheetData = $this->timesheetService->getTimesheetDayView($day, false, false);
            $defaultTimetype = array_filter($timetypes, function ($objTimeType) use ($aryTimesheetData) {
                return ($objTimeType->getId() == $aryTimesheetData['Timesheet']['default_timetypeid']);
            });
            $defaultTimetype = reset($defaultTimetype);
            $aryAssignedProjects = $aryTimesheetData['BookedHours']['bookedprojects'];
        }

        if(count($aryAssignedProjects) > 0){
            //$aryProjects = ['Staffed' => [], 'Available' => []];
            $aryProjectObjects = ['Staffed' => [], 'Available' => []];
        }else{
            //$aryProjects = [];
            $aryProjectObjects = [];
        }

        $aryProkectAssignments = $this->em->getRepository('SundialBundle:ProjectAssign')->getAssignedProjects($this->token->getUser()->getId());
        foreach($aryProkectAssignments as $objAssignment){
            $objProject = $objAssignment->getProject();
            if(count($aryAssignedProjects) > 0){
                if(in_array($objProject->getId(), $aryAssignedProjects)){
                    $aryProjectObjects['Staffed'][] = $objProject;
                }
                $aryProjectObjects['Available'][] = $objProject;
            }else{
                $aryProjectObjects[] = $objProject;
            }
        }

        $fcnSort = function($a,$b){
            return strcmp($a->getCustomer()->getName(), $b->getCustomer()->getName());
        };

        if(count($aryAssignedProjects) > 0){
            usort($aryProjectObjects['Staffed'], $fcnSort);
            usort($aryProjectObjects['Available'], $fcnSort);
        }else{
            usort($aryProjectObjects, $fcnSort);
        }

        $projectTaskRepo = $this->em->getRepository('SundialBundle:ProjectTask');

        $builder
            ->add('id', HiddenType::class)
            ->add('togglId', HiddenType::class)
            ->add('togglTime', HiddenType::class)
            ->add('togglProjectId', HiddenType::class)
            ->add('togglProjectName', HiddenType::class)
            ->add('timetype', EntityType::class, [
                'placeholder' => 'Select',
                'class' => 'SundialBundle:TimeType',
                'choices' => $timetypes,
                'data' => $defaultTimetype,
                'attr' => ['class' => 'timetype_select']
            ])
            ->add('project', EntityType::class, [
                'class' => 'SundialBundle:Project',
                'placeholder' => 'Select',
                'choices' => $aryProjectObjects,
                'attr' => ['class' => 'selectpicker'],
                'choice_label' => function ($proj) {
                    return $proj->getCustomer()->getName()." :: ".$proj->getName();
                }
            ])
            ->add('task', EntityType::class, [
                'class' => 'SundialBundle:ProjectTask',
                'placeholder' => 'Select Client First',
                'choices' => [],
                'attr' => ['disabled' => 'disabled']
            ])
            ->add('time', NumberType::class, [
                'precision' => 2,
                'attr' => ['step' => '.25', 'min' => 0, 'class' => 'time-entry']
            ])
            ->add('description', TextareaType::class, [
                'attr' => ['cols' => 40, 'rows' => 1, 'class' => 'description-entry'],
                'required' => false
            ])
            ->add('mapped', CheckboxType::class, [
                'label' => false,
                'required' => false
            ])
        ;
        $container = $this->container;
        $builder->addEventListener(FormEvents::POST_SET_DATA, function(FormEvent $event) use ($projectTaskRepo, $container, $entityUtility, $timetypes){
            $data = $event->getData();

            // remove the 'data' attribute on 'timetype' if there's form data.
            if($data && array_key_exists('timetype', $data) && !is_null($data['timetype'])){
                $form = $event->getForm();
                $form->remove('timetype');
                $form->add('timetype', EntityType::class, [
                    'placeholder' => 'Select',
                    'class' => 'SundialBundle:TimeType',
                    'choices' => $timetypes,
                    'attr' => ['class' => 'timetype_select']
                ]);
            }

            // override the projecttask if there's data
            if($data && array_key_exists('project', $data) && !is_null($data['project'])){
                $form = $event->getForm();
                $form->remove('task');
                $choices = $projectTaskRepo->getTasksForProject($data['project']);

                if(!$choices){
                    $choices = $entityUtility->fillTasksForProject($data['project']);
                }
                //dump($choices);exit;
                $form->add('task', EntityType::class, [
                    'class' => 'SundialBundle:ProjectTask',
                    'choices' => $choices,
                    'choice_label' => function ($task){
                        return $task->getIdNumber().'. '.$task->getName();
                    }
                ]);
            }
        });

        $builder->addEventListener(FormEvents::PRE_SUBMIT, function(FormEvent $event) use ($projectTaskRepo, $container, $entityUtility){
            $data = $event->getData();
            if(!is_null($data)){
                $choices = $projectTaskRepo->getTasksForProject($data['project']);
                if(!$choices){
                    $choices = $entityUtility->fillTasksForProject($data['project']);
                }
                $aryTasks = array_filter($choices, function($obj) use ($data){
                    return $obj->getId() == $data['task'];
                });
                $objTask = reset($aryTasks); // get the first and only object
                $event->getForm()->add('task', EntityType::class, [
                    'class' => 'SundialBundle:ProjectTask',
                    'choices' => $choices,
                    'data' => $objTask
                ]);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver){}

    public function getName()
    {
        return 'task_type';
    }

}

src/SundialBundle/Controller/ReportsController.php
<?php

namespace SundialBundle\Controller;


use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use SundialBundle\Entity\Budget;
use SundialBundle\Entity\FinancialReport;
use SundialBundle\Form\BudgetType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;


/**
 * Class ReportsController
 * @package SundialBundle\Controller
 * @Route("/reports")
 */
class ReportsController extends Controller
{

    /**
     * @Route("/", name="reports_dashboard")
     * @Security("has_role('ROLE_USER')")
     */
    public function dashboardAction(){

        return $this->render('SundialBundle:reports:dashboard.html.twig',[
            'reports' => $this->getDoctrine()->getRepository('SundialBundle:FinancialReport')->findBy(['user' => $this->getUser()])
        ]);
    }

    /**
     * @Route("/add", name="add_report")
     */
    public function addReportAction(Request $request){
        $projectRepo = $this->getDoctrine()->getRepository('SundialBundle:Project');
        $objReport = new FinancialReport();
        $objReport->setUser($this->getUser());
        $form = $this->createForm('financial_report_type', $objReport);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $objReport = $form->getData();
            $objReport->setProject($projectRepo->find($objReport->getProject()));
            $em = $this->getDoctrine()->getManager();
            $em->persist($objReport);
            $em->flush();
            $this->addFlash('success', 'Your report was created.  Please enter your budget information below.');
            return $this->redirectToRoute('report_budget', ['id'=>$objReport->getId()]);
        }
        return $this->render('SundialBundle:reports:add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/budgets/{id}", name="report_budget", requirements={"id":"\d+"})
     */
    public function setBudgetAction(Request $request, $id){
        $objReportRepo = $this->getDoctrine()->getRepository('SundialBundle:FinancialReport');
        $report = $objReportRepo->find($id);
        $this->denyAccessUnlessGranted('edit', $report);
        $reportService = $this->get('app.financial_report_service');

        $form = $reportService->getBudgetForm($report);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $aryData = $form->getData();
            foreach($aryData as $arySingleBudget){
                $report->addTaskBudget($arySingleBudget[0]);
                //$em->persist($arySingleBudget[0]);
            }
            $em->persist($report);
            $em->flush();
            $this->addFlash('success', 'Your budgets were saved successfully.');
            return $this->redirectToRoute('financial_report_details', ['id'=>$report->getId()]);
        }
        return $this->render('SundialBundle:reports:budgets.html.twig', [
            'form' => $form->createView(),
            'report' => $report
        ]);
        //dump($aryData);exit;
    }

    /**
     * @Route("/view/{id}", name="financial_report_details", requirements={"id":"\d+"})
     */
    public function reportsViewAction(Request $request, $id){
        $service = $this->get('app.financial_report_service');
        $view = $service->getReportView($id);

        if(!$view){
            $this->addFlash('error', 'Sorry, we were unable to find that report.  Please try again');
            $this->redirectToRoute('reports_dashboard');
        }

        $form = $view['budgetForm'];
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            foreach($form->getData() as $array){
                foreach($array as $objBudget){
                    $em->persist($objBudget);
                }
            }
            $em->flush();
            return $this->redirectToRoute('financial_report_details', ['id' => $id]);
        }else{
            $view['budgetForm'] = $view['budgetForm']->createView();
        }

        $form = $view['reportForm'];
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($form->getData());
            $em->flush();
            return $this->redirectToRoute('financial_report_details', ['id' => $id]);
        }else{
            $view['reportForm'] = $view['reportForm']->createView();
        }


        if($this->denyAccessUnlessGranted('view', $view['report'])){

        }
        return $this->render('SundialBundle:reports:view.html.twig', [
            'report' => $view
        ]);
    }

}

src/SundialBundle/Resources/views/reports/tabs/budgets.html.twig
<div class="panel panel-primary">
    <div class="panel-heading">
        Budgets
    </div>
    <div class="panel-body">
        {% set form = report.budgetForm %}
        {% include 'SundialBundle:reports/inc:budgets_form.html.twig' %}
    </div>
</div>

src/SundialBundle/Resources/views/reports/tabs/home.html.twig
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Billable Status
            </div>
            <div class="panel-body">
                <table class="table table-condensed">
                    <tr>
                        <th>Time Type</th>
                        <th>Total</th>
                        <th>Percent</th>
                    </tr>
                    {% for row in report.timeBreakdown.breakdown %}
                        <tr>
                            <td>{{ row.type }}</td>
                            <td>{{ row.hours_sum }}</td>
                            <td>{{ ((row.hours_sum / report.timeBreakdown.total) * 100)|round(2) }} %</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="panel-footer">
                Total:
                <span class="pull-right">
                    {{ report.timeBreakdown.total }} hrs
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Billable Percentage
            </div>
            <div class="panel-body">
                <table class="table table-condensed">
                    <tr>
                        <th>Time Type</th>
                        <th>Time</th>
                        <th>Percentage</th>
                    </tr>
                    <tr>
                        <td>Billable</td>
                        <td>
                            {% if report.billableVsNonbill.billable is not null %}
                                {{ report.billableVsNonbill.billable }}
                            {% else %}
                                0.00
                            {% endif %}
                        </td>
                        <td>{{ ((report.billableVsNonbill.billable/report.billableVsNonbill.total)*100)|number_format(2, '.', ',') }}%</td>
                    </tr>
                    <tr>
                        <td>Non Billable</td>
                        <td>{{ report.billableVsNonbill.nonbillable }}</td>
                        <td>{{ ((report.billableVsNonbill.nonbillable/report.billableVsNonbill.total)*100)|number_format(2, '.', ',') }}%</td>
                    </tr>
                    <tr>
                        <td>Total</td>
                        <td>{{ report.billableVsNonbill.total }}</td>
                        <td>{{ ((report.billableVsNonbill.total/report.billableVsNonbill.total)*100)|number_format(2, '.', ',') }}%</td>
                    </tr>
                </table>
            </div>
            {#<div class="panel-footer">
                Total:
                <span class="pull-right">
                    {{ sum }} hrs
                </span>
            </div>#}
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        Time By Task This Month
    </div>
    <div class="panel-body">
        <table class="table table-condensed time-by-task-for-month">
            <thead>
            <tr>
                <th>Task</th>
                {% for type in report.timetypes %}
                    <th>{{ type.type }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% if report.tasksForMonth|length > 0 %}
                {% set sum = 0 %}
                {% for row in report.tasksForMonth %}
                    <tr>
                        <td>{{ row.name }}</td>
                        {% for type in report.timetypes %}
                            <td>
                                {% if row.times[type.id] is defined %}
                                    {{ row.times[type.id] }}
                                {% else %}
                                    0.00
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                    {#{% set sum = sum + row.hours_sum %}#}
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7" class="text-center">There are no time records this month</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        Time By Task
    </div>
    <div class="panel-body">
        <table class="table table-condensed time-by-task">
            <thead>
            <tr>
                <th>Task</th>
                {% for type in report.timetypes %}
                    <th>{{ type.type }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% set sum = 0 %}
            {% for row in report.dataByTask %}
                <tr>
                    <td>{{ row.name }}</td>
                    {% for type in report.timetypes %}
                        <td>
                            {% if row.times[type.id] is defined %}
                                {{ row.times[type.id] }}
                            {% else %}
                                0.00
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
                {#{% set sum = sum + row.hours_sum %}#}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        Time By User
    </div>
    <div class="panel-body">
        <table class="table table-condensed time-by-task">
            <thead>
            <tr>
                <th>User</th>
                {% for type in report.timetypes %}
                    <th>{{ type.type }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% set sum = 0 %}
            {% for row in report.dataByUser %}
                <tr>
                    <td>{{ row.name }}</td>
                    {% for type in report.timetypes %}
                        <td>
                            {% if row.times[type.id] is defined %}
                                {{ row.times[type.id] }}
                            {% else %}
                                0.00
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
                {#{% set sum = sum + row.hours_sum %}#}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

src/SundialBundle/Resources/views/reports/tabs/projections.html.twig
<div class="panel panel-primary">
    <div class="panel-heading">
        Budget Vs Actual
    </div>
    <div class="panel-body">

        {% if report.ratesExist == false %}
            <p>Cost information is not shown because there is no rate information entered in Open Air.</p>
        {% endif %}
        <table class="table table-condensed">
            <tr>
                <th>Task</th>
                <th class="success">Budgeted Hours</th>
                {% if report.ratesExist %}
                    <th class="success">Budgeted Cost</th>
                {% endif %}
                <th class="info">Hours Spent</th>
                {% if report.ratesExist %}
                    <th class="info">Cost Spent</th>
                {% endif %}
                <th class="warning">Hours Remaining</th>
                {% if report.ratesExist %}
                    <th class="warning">Cost Remaining</th>
                {% endif %}
            </tr>
            {% for budget in report.budgetVsActuals %}
                {% set hours_remaining = (budget.budget.hours - budget.total_hours_worked) %}
                {% set cost_remaining = (budget.budget.dollars - budget.cost) %}
                <tr class="{% if hours_remaining < 0 or cost_remaining < 0 %}danger{% endif %}">
                    <td>
                        {{ budget.budget.task.name }}
                        {% if budget.budget.task.parent is not null %}
                            ({{ budget.budget.task.parent.name }})
                        {% endif %}
                    </td>
                    <td class="success">{{ budget.budget.hours }}</td>
                    {% if report.ratesExist %}
                        <td class="success">${{ budget.budget.dollars }}</td>
                    {% endif %}
                    <td class="info">
                        {% if budget.total_hours_worked is not null %}
                            {{ budget.total_hours_worked }}
                        {% else %}
                            0.00
                        {% endif %}
                    </td>
                    {% if report.ratesExist %}
                        <td class="info">
                            ${{ budget.cost }}
                        </td>
                    {% endif %}
                    <td class="warning">{{ hours_remaining|number_format(2, '.', ',') }}</td>
                    {% if report.ratesExist %}
                        <td class="warning">
                            ${{ cost_remaining|number_format(2, '.', ',') }}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

src/SundialBundle/Resources/views/reports/tabs/rawdata.html.twig
<div class="panel panel-primary">
    <div class="panel-heading">
        Budget Vs Actual
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered table-hover rawData {#table table-condensed#}">
            <thead>
            <tr>
                <th>Time Type</th>
                <th>Person</th>
                <th>Task</th>
                <th>Description</th>
                <th>Hours</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for row in report.rawData %}
                <tr>
                    <td>{{ row.timeType.type }}</td>
                    <td>{{ row.user}}</td>
                    <td>{{ row.projectTask }}</td>
                    <td>{{ row.description }}</td>
                    <td>{{ row.decimalHours }}</td>
                    <td>{{ row.date.format('Y-m-d') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {#<div class="panel-footer">
        Total:
        <span class="pull-right">
            {{ sum }} hrs
        </span>
    </div>#}
</div>

src/SundialBundle/Resources/views/reports/tabs/settings.html.twig
<p>
    <button class="btn btn-success btn-lg btn-block run-report">Run Report Now</button>
</p>
{{ form_start(report.reportForm) }}
<div class="panel panel-primary">
    <div class="panel-heading">
        Budgets
    </div>
    <div class="panel-body">
        {{ form_row(report.reportForm.name) }}
        {{ form_row(report.reportForm.budgetHigh) }}
        {{ form_row(report.reportForm.budgetLow) }}
        {{ form_row(report.reportForm.averageRate) }}
        {{ form_row(report.reportForm.hoursToFinish) }}
    </div>
    <div class="panel-footer">
        {{ form_row(report.reportForm.create, {'label' : 'Update'}) }}
    </div>
</div>
{{ form_end(report.reportForm) }}